### PR TITLE
Page search & character strip

### PR DESCRIPTION
**Pull request by mikeybeck**
Updated readme to document page search. 
Added a plugin to strip characters that will cause invalid JSON.

(Sorry about the use of a plugin; I'm new to Ruby & Jekyll, and couldn't figure out a better way to remove some characters from the JSON)

### CODE REVIEW

**Comment by christian-fei** [comment]
Thank you very much!! :)

**Comment by mikeybeck** [comment]
No worries, thank you for making this!

**Comment by daviddarnes** [comment]
Doesn't the [jsonify filter](http://jekyllrb.com/docs/templates/) in liquid do this anyway? This .rb file won't be useable on Jekyll sites hosted with GitHub Pages.

**Comment by mikeybeck** [comment]
Oh man I can't believe I missed that!  What an idiot.  Ok I'll confirm the jsonify filter works and remove the plugin

**Comment by daviddarnes** [comment]
@mikeybeck great stuff, thanks for taking the time to contribute :)

**Pull request merged**
