### PR TITLE
whitelist specific keys to prevent re-rendering search results

### PR DESCRIPTION
**Pull request by egladman**
This addresses issue #55.

This whitelists the following keys:
- up/down/left/right arrow keys
- modifier key
- shift key
- enter key
- caps lock key

`event.which` is [technically deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which), however it still is the 'go-to' means of detecting keyevents until `KeyboardEvent.code` [gains support](http://caniuse.com/#search=KeyboardEvent.code). Even jQuery still uses `event.which`. 

If your curious how these changes effect the scripts behavior, checkout [this site](https://opensource.osu.edu/) where I'm using this patched version.

Thanks for creating and maintaining this project

### CODE REVIEW

**Comment by christian-fei** [comment]
This is really great, thank you so much!
Will review the code as soon as I can

**Comment by egladman** [comment]
Any updates?

**Comment by christian-fei** [comment]
Hello!
yeah could you convert the eval thing in a simple check whether the key isn't contained in the `whitelist` array?

like:

```
if( whitelist.indexOf(e.which) === -1 )
```

**Comment by egladman** [comment]
Nice suggestion. I wish I thought of that myself.

**Comment by christian-fei** [comment]
thank you very much! you rock :+1:

**Pull request merged**
