### PR TITLE
Build fixes and updates

### LINKED ISSUE #80: Add license header to dist files

### LINKED ISSUE #81: Move test files outside of src folder

### PR DESCRIPTION
**Pull request by XhmikosR**
@christian-fei: I don't have the time to split this. Also, I can't run `npm test` since I'm on Windows and `m.test` fails.

That being said, the build seems to be fine but please verify.

After this is merged, you will need to create a new patch release.

Fixes #80 
Fixes #81

### CODE REVIEW

**Comment by XhmikosR** [comment]
Freaking Hound... Where have you configured Hound @christian-fei ?

**Comment by XhmikosR** [comment]
@christian-fei: I'm done with my changes. Only Hound needs to either be removed or properly configured from your side.

Otherwise, test, merge and release a new version :)

**Comment by christian-fei** [comment]
thank you!

**Comment by XhmikosR** [comment]
@christian-fei: don't forget to release a new version :)

**Pull request merged**
