### PR TITLE
Assorted tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
@christian-fei:

1.  I removed Hound because we already test everything in Travis plus Hound didn't do anything with the current setup; its eslint is disabled by default. So if you agree remove the repository hook
2. I bumped the version to 1.6.0 so you can publish/make the tag after merging

Let me know if you need me to change anything.

### CODE REVIEW

**Comment by XhmikosR** [comment]
ping @christian-fei

**Comment by XhmikosR** [comment]
@christian-fei: friendly bump

**Comment by XhmikosR** [comment]
@christian-fei: bump

**Comment by christian-fei** [comment]
Thank you @XhmikosR !

**Comment by XhmikosR** [comment]
@christian-fei: don't forget to remove Hound from the repo and publish the git tag/github release/npm.

**Pull request merged**
