### PR TITLE
Correct multi word search to AND

### PR DESCRIPTION
**Pull request by JackGruber**
- Multiple word search is OR combined and not AND
- Remove leading and trailing whitespace

### CODE REVIEW

**Comment by marabesi** [comment]
Travis build is failing in the js code style (https://travis-ci.org/christian-fei/Simple-Jekyll-Search/builds/450423148?utm_source=github_status&utm_medium=notification)

It is complaining that you should use `===` instead of `==`

**Comment by JackGruber** [comment]
Don't know me so well, but === and !== is only for boolean values?!

**Comment by christian-fei** [comment]
@JackGruber `==` and `!=` converts (`coerces`) the types and then does an equality check. `===` and `!==` is safer and called `strict` equality operator, the type must be the same as the value of both operands

**Comment by christian-fei** [comment]
Thank you @JackGruber !

**Pull request merged**
