### PR TITLE
Reorder the `readyState` check.

### LINKED ISSUE #49: IE 9 error c00c023f
Hi.

We are getting a script error with IE9 in Bootstrap.

```
SCRIPT575: Could not complete the operation due to error c00c023f. 
jekyll-search.js, line 1 character 625
```

This might help: http://stackoverflow.com/questions/7287706/ie-9-javascript-error-c00c023f

### PR DESCRIPTION
**Pull request by XhmikosR**
Apparently IE9 does something weird here so since the order matters check for `readyState` first. Other browsers don't seem to have any issues either way.

Fixes #49.

/CC @christian-fei

### CODE REVIEW

**Comment by christian-fei** [comment]
You're awesome, thanks!
Have a good week-end :)

**Comment by XhmikosR** [comment]
No problem, it was easier than I expected :)

Will you make a new release? Or should I use the master code in Bootstrap?

**Comment by christian-fei** [comment]
Yes about to make a release :)

**Comment by christian-fei** [comment]
@XhmikosR released 1.1.0

**Comment by XhmikosR** [comment]
Damn, just update to 1.0.9.

**Comment by XhmikosR** [comment]
Oh, it seems it's the same with just the version number bumped so it's all good :)

**Pull request merged**
